### ISSUE TITLE
width and height are missing from BootstrapSwitchButtonProps type

### ISSUE THREAD

**Issue by evark** [gitbrent/bootstrap-switch-button-react#11]
Typescript complains  when width/height props are passed in  BootstrapSwitchButton.

**Comment by gitbrent** [comment]
Thanks @evark 

Somehow i completely missed these props.

Fixed:

<img width="748" alt="Screen Shot 2019-10-22 at 22 43 25" src="https://user-images.githubusercontent.com/7218970/67355704-87a36580-f51d-11e9-87b5-4181a01fc996.png">
