### ISSUE TITLE
Size attribute not released yet

### ISSUE THREAD

**Issue by iamisti** [gitbrent/bootstrap-switch-button-react#13]
Hi!
 
I get a TS error, because one of the TS interface wasn't updated yet. It's already on master branch, but haven't been released yet.

Currently i have this with v1.1.0 :
```
interface BootstrapSwitchButtonProps {
  /**
   * Function to call when the SwitchButton is changed
   */
  onChange?: (checked: boolean) => void;
  checked?: boolean;
  onlabel?: string;
  offlabel?: string;
  offstyle?: Colors | ColorsOutline;
  onstyle?: Colors | ColorsOutline;
  style?: string;
}
```

and what's missing is a "size" property. 
Could you please release a new version?

**Comment by gitbrent** [comment]
Thanks @iamisti 

Fixed in upcoming 1.2.0 release
