### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by choweiyuan** [gitbrent/bootstrap-switch-button-react#4]
Hi

I noticed this commit which gives typescript support https://github.com/gitbrent/bootstrap-switch-button-react/commit/0881898ac9d7f19306524b615fc2cbb4178d86cc

Any timeline on the next release? I'm currently working around by using`// @ts-ignore`

**Comment by gitbrent** [comment]
Thanks for the reminder!

Version `1.1.0` has been released.
